[package]
name = "rational"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
num = { version = "0.4.0", features = ["serde"] }
serde = { version = "1.0.126", features = ["derive"] }
thiserror = "1.0.26"
serde_json = { version = "1.0.64", features = ["arbitrary_precision"] }
