[[constants]]
names = ["earth", "orbit", "distance"]
unit = "au"
value = "1"

[[constants]]
names = ["earth", "mass"]
unit = "kg"
value = "5.972e24"

[[constants]]
names = ["earth", "orbital", "period"]
unit = "yr"
value = "1"

[[constants]]
names = ["earth", "solar", "day"]
unit = "dy"
value = "1"
