[[constants]]
names = ["jupiter", "orbit", "distance"]
unit = "au"
value = "5.203"

[[constants]]
names = ["jupiter", "mass"]
unit = "kg"
value = "1.8992e27"

[[constants]]
names = ["jupiter", "orbital", "period"]
unit = "yr"
value = "11.86"
