[[constants]]
names = ["mercury", "orbit", "distance"]
unit = "au"
value = "0.387"

[[constants]]
names = ["mercury", "mass"]
unit = "kg"
value = "3.302e23"

[[constants]]
names = ["mercury", "orbital", "period"]
unit = "dy"
value = "87.969"
