[[constants]]
names = ["pluto", "orbit", "distance"]
unit = "au"
value = "49.3"

[[constants]]
names = ["pluto", "mass"]
unit = "kg"
value = "1.309e22"

[[constants]]
names = ["pluto", "orbital", "period"]
unit = "yr"
value = "248"
