[[constants]]
names = ["venus", "orbit", "distance"]
unit = "au"
value = "0.723"

[[constants]]
names = ["venus", "mass"]
unit = "kg"
value = "4.870e24"

[[constants]]
names = ["venus", "orbital", "period"]
unit = "dy"
value = "224.7"
