[[units]]
type = "base"
variant = "Second"
names = ["s", "sec", "second", "seconds"]
unit = "Unit::Second"
[[units]]
type = "base"
variant = "Meter"
names = ["m", "metre", "meter", "meters"]
unit = "Unit::Meter"
[[units]]
type = "base"
variant = "Gram"
names = ["g", "gram"]
unit = "Unit::KiloGram"
prefix_bias = -3
[[units]]
type = "base"
variant = "Ampere"
names = ["A", "ampere", "amperes"]
unit = "Unit::Ampere"
[[units]]
type = "base"
variant = "Kelvin"
names = ["K", "kelvin", "kelvins"]
unit = "Unit::Kelvin"
[[units]]
type = "base"
variant = "Mole"
names = ["mol", "mols", "mole", "moles"]
unit = "Unit::Mole"
[[units]]
type = "base"
variant = "Candela"
names = ["cd", "candela", "candelas"]
unit = "Unit::Candela"
[[units]]
type = "base"
variant = "Byte"
names = ["B", "byte"]
unit = "Unit::Byte"

[[units]]
type = "derived"
id = "0x3cea0000"
variant = "Minute"
names = ["minute", "minutes", "min", "mins"]
name = "time::MINUTE"
[[units]]
type = "derived"
id = "0x3cea0001"
variant = "Hour"
names = ["h", "hr", "hour", "hours"]
name = "time::HOUR"
[[units]]
type = "derived"
id = "0x3cea0003"
variant = "Day"
names = ["dy", "day", "days"]
name = "time::DAY"
[[units]]
type = "derived"
id = "0x3cea0004"
variant = "Week"
names = ["wk", "week", "weeks"]
name = "time::WEEK"
[[units]]
type = "derived"
id = "0x3cea0005"
variant = "Month"
names = ["mth", "mths", "month", "months"]
name = "time::MONTH"
[[units]]
type = "derived"
id = "0x3cea1000"
variant = "Year"
names = ["y", "yr", "yrs", "year", "years"]
name = "time::YEAR"
[[units]]
type = "derived"
id = "0x3cea2000"
variant = "Decade"
names = ["decade", "decades"]
name = "time::DECADE"
[[units]]
type = "derived"
id = "0x3cea3000"
variant = "Century"
names = ["century", "centuries"]
name = "time::CENTURY"
[[units]]
type = "derived"
id = "0x3cea4000"
variant = "Millenium"
names = ["M", "millenium", "milleniums", "millenia"]
name = "time::MILLENIUM"

[[units]]
type = "derived"
id = "0x7b15d4d8"
variant = "Tonne"
names = ["ton", "tons", "tonne", "tonnes"]
name = "mass::TONNE"
[[units]]
type = "derived"
id = "0x95583f60"
variant = "Dalton"
names = ["Da", "dalton", "daltons"]
name = "mass::DALTON"

[[units]]
type = "derived"
id = "0x1c108ba2"
variant = "Litre"
names = ["l", "L", "litre", "litres"]
name = "volume::LITRE"
[[units]]
type = "derived"
id = "0xb36964a0"
variant = "CubicCentimetre"
names = ["cc"]
name = "volume::CUBIC_CENTIMETER"
[[units]]
type = "derived"
id = "0x1c108ba3"
variant = "Gallon"
names = ["gal", "gals", "gallon", "gallons"]
name = "volume::GALLON"
[[units]]
type = "derived"
id = "0x1c108ba4"
variant = "Pint"
names = ["pint", "pints"]
name = "volume::PINT"
[[units]]
type = "derived"
id = "0x1c108ba5"
variant = "Quart"
names = ["quart", "quarts"]
name = "volume::QUART"
[[units]]
type = "derived"
id = "0x1c108ba6"
variant = "Cup"
names = ["cup", "cups"]
name = "volume::CUP"
[[units]]
type = "derived"
id = "0x1c108ba7"
variant = "Gill"
names = ["gill", "gills"]
name = "volume::GILL"
[[units]]
type = "derived"
id = "0x1c108ba8"
variant = "FuildOunce"
names = ["floz", "flozs"]
name = "volume::FLUID_OUNCE"
[[units]]
type = "derived"
id = "0x1c108ba9"
variant = "TableSpoon"
names = ["tbsp", "tbsps", "tablespoon", "tablespoons"]
name = "volume::TABLE_SPOON"
[[units]]
type = "derived"
id = "0x1c108baa"
variant = "TeaSpoon"
names = ["tsp", "tsps", "teaspoon", "teaspoons"]
name = "volume::TEA_SPOON"

[[units]]
type = "derived"
id = "0xbf2e000f"
variant = "Hectare"
names = ["ha", "hectare", "hectares"]
name = "area::HECTARE"
[[units]]
type = "derived"
id = "0xf153d092"
variant = "Perch"
names = ["perch", "perches"]
name = "area::PERCH"
[[units]]
type = "derived"
id = "0x20541ce3"
variant = "Rood"
names = ["rood", "roods"]
name = "area::ROOD"
[[units]]
type = "derived"
id = "0xe44777d2"
variant = "Acre"
names = ["acre", "acres"]
name = "area::ACRE"

[[units]]
type = "derived"
id = "0xaab4f36c"
variant = "Acceleration"
names = ["a", "acc", "acceleration"]
name = "ACCELERATION"
[[units]]
type = "derived"
id = "0x47dd35dc"
variant = "Velocity"
names = ["v", "vel", "velocity"]
name = "VELOCITY"
[[units]]
type = "derived"
id = "0xb82b2151"
variant = "Gforce"
names = ["gforce", "g-force"]
name = "GFORCE"
[[units]]
type = "derived"
id = "0x150ab031"
variant = "Newton"
names = ["N", "newton", "newtons"]
name = "NEWTON"
[[units]]
type = "derived"
id = "0xd575976d"
variant = "Pascal"
names = ["Pa", "pascal", "pascals"]
name = "PASCAL"

[[units]]
type = "derived"
id = "0xe0796773"
variant = "Joule"
names = ["J", "joule"]
name = "energy::JOULE"
[[units]]
type = "derived"
id = "0xcf847a94"
variant = "Btu"
names = ["btu"]
name = "energy::BTU"
[[units]]
type = "derived"
id = "0x007adc81"
variant = "Electronvolt"
names = ["eV", "electronvolt", "electronvolts"]
name = "energy::ELECTRONVOLT"

[[units]]
type = "derived"
id = "0xa977f890"
variant = "Watt"
names = ["W", "watt", "watts"]
name = "WATT"
[[units]]
type = "derived"
id = "0xf57d5095"
variant = "Coulomb"
names = ["C", "coulomb", "coulombs"]
name = "COULOMB"
[[units]]
type = "derived"
id = "0x27475ce0"
variant = "Volt"
names = ["V", "volt", "volts"]
name = "VOLT"
[[units]]
type = "derived"
id = "0xcea46875"
variant = "Farad"
names = ["F", "farad", "farads"]
name = "FARAD"
[[units]]
type = "derived"
id = "0x4c6815d9"
variant = "Ohm"
names = ["Ω", "ohm", "ohms"]
name = "OHM"
[[units]]
type = "derived"
id = "0xd87739a9"
variant = "Siemens"
names = ["S", "siemens"]
name = "SIEMENS"
[[units]]
type = "derived"
id = "0x69ca6c0a"
variant = "Weber"
names = ["Wb", "weber", "webers"]
name = "WEBER"
[[units]]
type = "derived"
id = "0x731514a7"
variant = "Tesla"
names = ["T", "tesla", "teslas"]
name = "TESLA"
[[units]]
type = "derived"
id = "0xef26a9d5"
variant = "Henry"
names = ["H", "henry", "henrys", "henries"]
name = "HENRY"
[[units]]
type = "derived"
id = "0x359318c2"
variant = "Lumen"
names = ["lm", "lumen", "lumens"]
name = "LUMEN"
[[units]]
type = "derived"
id = "0xad603e6d"
variant = "Lux"
names = ["lx", "lux"]
name = "LUX"
[[units]]
type = "derived"
id = "0x7c25d25c"
variant = "Becquerel"
names = ["Bq", "becquerel", "becquerels"]
name = "BECQUEREL"
[[units]]
type = "derived"
id = "0x6008fcb5"
variant = "Gray"
names = ["Gy", "gray", "grays"]
name = "GRAY"
[[units]]
type = "derived"
id = "0xcd0fdf3b"
variant = "Sievert"
names = ["Sv", "sievert", "sieverts"]
name = "SIEVERT"
[[units]]
type = "derived"
id = "0x9645d02f"
variant = "Katal"
names = ["kat", "katal", "katals"]
name = "KATAL"

[[units]]
type = "derived"
id = "0x8e8393e6"
variant = "LightSpeed"
names = ["c"]
name = "velocity::LIGHT_SPEED"
[[units]]
type = "derived"
id = "0xc8545958"
variant = "Knot"
names = ["kt", "knot", "knots"]
name = "velocity::KNOT"

[[units]]
type = "derived"
id = "0xc790db55"
variant = "Au"
names = ["au"]
name = "length::AU"
[[units]]
type = "derived"
id = "0x50d53fb0"
variant = "Fathom"
names = ["ftm", "fathom", "fathoms"]
name = "length::FATHOM"
[[units]]
type = "derived"
id = "0xd9192122"
variant = "Cable"
names = ["cable", "cables"]
name = "length::CABLE"
[[units]]
type = "derived"
id = "0xd767fd82"
variant = "NauticalMile"
names = ["NM", "nmi"]
name = "length::NAUTICAL_MILE"
[[units]]
type = "derived"
id = "0x9618566f"
variant = "Link"
names = ["link", "links"]
name = "length::LINK"
[[units]]
type = "derived"
id = "0x7ad5cf6d"
variant = "Rod"
names = ["rd", "rod", "rods"]
name = "length::ROD"
[[units]]
type = "derived"
id = "0xd3c90010"
variant = "Thou"
names = ["th", "thou", "thous"]
name = "length::THOU"
[[units]]
type = "derived"
id = "0xd3c90020"
variant = "Barleycorn"
names = ["Bc", "barleycorn", "barleycorns"]
name = "length::BARLEYCORN"
[[units]]
type = "derived"
id = "0xd3c90000"
variant = "Inch"
names = ["in", "inch", "inches"]
name = "length::INCH"
[[units]]
type = "derived"
id = "0xd3c90030"
variant = "Hand"
names = ["hand", "hands"]
name = "length::HAND"
[[units]]
type = "derived"
id = "0xd3c90001"
variant = "Feet"
names = ["ft", "feet", "feets"]
name = "length::FOOT"
[[units]]
type = "derived"
id = "0xd3c90002"
variant = "Yard"
names = ["yd", "yard", "yards"]
name = "length::YARD"
[[units]]
type = "derived"
id = "0xe8db8915"
variant = "Chain"
names = ["ch", "chain", "chains"]
name = "length::CHAIN"
[[units]]
type = "derived"
id = "0xd3c90040"
variant = "Furlong"
names = ["fur", "furlong", "furlongs"]
name = "length::FURLONG"
[[units]]
type = "derived"
id = "0xd3c90003"
variant = "Mile"
names = ["mi", "mile", "miles"]
name = "length::MILE"
[[units]]
type = "derived"
id = "0xd3c90004"
variant = "League"
names = ["lea", "league", "leagues"]
name = "length::LEAGUE"

[[units]]
type = "derived"
id = "0xf4321939"
variant = "Grain"
names = ["gr", "grain", "grains"]
name = "mass::GRAIN"
[[units]]
type = "derived"
id = "0xa3592b8c"
variant = "Drachm"
names = ["dr", "drachm", "drachms"]
name = "mass::DRACHM"
[[units]]
type = "derived"
id = "0x7c3b47da"
variant = "Ounce"
names = ["oz", "ounce", "ounces"]
name = "mass::OUNCE"
[[units]]
type = "derived"
id = "0xe0482a36"
variant = "Pound"
names = ["lb", "pound", "pounds"]
name = "mass::POUND"
[[units]]
type = "derived"
id = "0xc827fd0d"
variant = "Stone"
names = ["st", "stone", "stones"]
name = "mass::STONE"
[[units]]
type = "derived"
id = "0x20f6787b"
variant = "Quarter"
names = ["qr", "qtr", "quarter", "quarters"]
name = "mass::QUARTER"
[[units]]
type = "derived"
id = "0xf97a5980"
variant = "Hundredweight"
names = ["cwt", "hundredweight", "hundredweights"]
name = "mass::HUNDREDWEIGHT"
[[units]]
type = "derived"
id = "0xccbb6466"
variant = "ImperialTon"
names = ["t"]
name = "mass::TON"
[[units]]
type = "derived"
id = "0x28eaf41b"
variant = "Slug"
names = ["slug", "slugs"]
name = "mass::SLUG"

[[units]]
type = "derived"
id = "0xde39ff06"
variant = "Celsius"
names = ["°C", "celsius"]
name = "temperature::CELSIUS"
[[units]]
type = "derived"
id = "0x3a824baa"
variant = "Fahrenheit"
names = ["°F","fahrenheit"]
name = "temperature::FAHRENHEIT"

[[units]]
type = "derived"
id = "0x445f9706"
variant = "SpecificImpulse"
names = ["sp"]
name = "SPECIFIC_IMPULSE"

[[prefixes]]
variant = "Yotta"
names = ["Y", "yotta"]
prefix = "Prefix::YOTTA"
[[prefixes]]
variant = "Zetta"
names = ["Z", "zetta"]
prefix = "Prefix::ZETTA"
[[prefixes]]
variant = "Exa"
names = ["E", "exa"]
prefix = "Prefix::EXA"
[[prefixes]]
variant = "Peta"
names = ["P", "peta"]
prefix = "Prefix::PETA"
[[prefixes]]
variant = "Tera"
names = ["T", "tera"]
prefix = "Prefix::TERA"
[[prefixes]]
variant = "Giga"
names = ["G", "giga"]
prefix = "Prefix::GIGA"
[[prefixes]]
variant = "Mega"
names = ["M", "mega"]
prefix = "Prefix::MEGA"
[[prefixes]]
variant = "Kilo"
names = ["k", "kilo"]
prefix = "Prefix::KILO"
[[prefixes]]
variant = "Hecto"
names = ["h", "hecto"]
prefix = "Prefix::HECTO"
[[prefixes]]
variant = "Deca"
names = ["da", "deca"]
prefix = "Prefix::DECA"
[[prefixes]]
variant = "Deci"
names = ["d", "deci"]
prefix = "Prefix::DECI"
[[prefixes]]
variant = "Centi"
names = ["c", "centi"]
prefix = "Prefix::CENTI"
[[prefixes]]
variant = "Milli"
names = ["m", "milli"]
prefix = "Prefix::MILLI"
[[prefixes]]
variant = "Micro"
names = ["μ", "micro"]
prefix = "Prefix::MICRO"
[[prefixes]]
variant = "Nano"
names = ["n", "nano"]
prefix = "Prefix::NANO"
[[prefixes]]
variant = "Pico"
names = ["p", "pico"]
prefix = "Prefix::PICO"
[[prefixes]]
variant = "Femto"
names = ["f", "femto"]
prefix = "Prefix::FEMTO"
[[prefixes]]
variant = "Atto"
names = ["a", "atto"]
prefix = "Prefix::ATTO"
[[prefixes]]
variant = "Zepto"
names = ["z", "zepto"]
prefix = "Prefix::ZEPTO"
[[prefixes]]
variant = "Yocto"
names = ["y", "yocto"]
prefix = "Prefix::YOCTO"
