[[constants]]
names = ["au", "distance to earth", "orbit of earth", "earth orbit"]
unit = "au"
value = "1"

[[constants]]
names = ["distance london to new york"]
unit = "km"
value = "5571.55"

[[constants]]
names = ["observable universe"]
unit = "Ym"
value = "880"
