[[constants]]
names = ["au", "distance", "orbit", "earth"]
unit = "au"
value = "1"

[[constants]]
names = ["distance", "london", "new", "york"]
unit = "km"
value = "5571.55"

[[constants]]
names = ["observable", "universe", "size"]
unit = "Ym"
value = "880"
