[[constants]]
tokens = ["distance", "london", "new", "york"]
description = "Distance between London and New York"
unit = "km"
value = "5571.55"

[[constants]]
tokens = ["observable", "universe", "size"]
description = "Size of the observable universe"
unit = "Ym"
value = "880"
