[[constants]]
names = ["c", "lightspeed", "speed", "light"]
unit = "c"
value = "1"

[[constants]]
names = ["standard", "gravity", "g0"]
unit = "m/s^2"
value = "9.80665"

[[constants]]
names = ["G", "gravitational", "constant"]
unit = "m^3/kgs^2"
value = "6.6743015e-11"
