name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      - run: cargo fmt --all -- --check
      - run: cargo test
